apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress-group
  name: wordpress-group
spec:
  replicas: 10
  selector:
    matchLabels:
      app: wordpress-group
  template:
    metadata:
      labels:
        app: wordpress-group
    spec:
      containers:
        - image: wordpress:beta-php8.3-apache
          name: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
